{
	"version": 1548936975,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/monster-sheet0.png",
		"images/monster-sheet1.png",
		"images/monster-sheet2.png",
		"images/door-sheet0.png",
		"images/door-sheet1.png",
		"images/tiledbackground2.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/door3-sheet0.png",
		"images/door2-sheet0.png",
		"images/door2-sheet1.png",
		"images/tiledbackground3.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/boss-sheet0.png",
		"images/tiledbackground4.png",
		"media/กระโดด3 (online-audio-converter.com).ogg",
		"media/กระโดดน่ารัก (online-audio-converter.com).ogg",
		"media/ตาย (online-audio-converter.com).ogg",
		"media/ตาย2 (online-audio-converter.com).ogg",
		"media/เปลี่ยนด่าน2 (online-audio-converter.com).ogg",
		"media/undertale sound effect - attack hit.m4a",
		"media/undertale sound effect - attack hit.ogg",
		"media/youtube poop sound effect die_.m4a",
		"media/youtube poop sound effect die_.ogg",
		"media/bg-loop.m4a",
		"media/bg-loop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}